name: Racket Publish

on:
  push:
    branches: ["develop"]
    paths:
      - "**publish.yml"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: "x64"
          distribution: "full"
          variant: "CS"
          version: "stable"
      - name: Build
        run: xvfb-run -a make
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.event.repository.name }}
          publish_branch: gh-pages
